version: '3.8'

services:
  webportal:
    image: specify-webportal
    container_name: webportal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/webportal.specifycloud.org:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - /var/www:/var/www
      - ./specify_exports:/home/specify/webportal-installer/specify_exports
      - ./custom-images:/home/specify/custom-images
    restart: unless-stopped
